project:
  type: website
  output-dir: docs

website:
  title: "Liam Quach"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd # add your listing page file to your navbar, just like you would any other new web page

format:
  html:
    html:
    theme: 
      light: mintyx
      dark: solar
    css: styles.css
    toc: true
    page-layout: full



      